<?php

namespace rubenrubiob\PoemBundle\Entity\Poem;

/**
 * PoemRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PoemRepository extends \Doctrine\ORM\EntityRepository
{
}
